### ISSUE TITLE
Better sales tracking

### ISSUE THREAD

**Issue by msmaiaa** [msmaiaa/csgo-brpanel#11]
- [x] Modify sales table, add purchase_type and additional_info
- [x] Create a sale record when a purchase is created, not just only when its fulfilled
- [x] Update the record on state change (failed/fulfilled)
- [x] Send an email to the customer (if he has one) about the order status changes 

For the notification system, we need to keep track of what the user bought and some extra data to show on the server. Ex:
- purchase_type: "cargo", additional_info: "Admin"
- purchase_type: "coins", additional_info: "30.000"
